In [ ]:
Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in 
sklearn.datasets.

In [71]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

x,y=load_iris(return_X_y=True)

X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3, random_state=0)
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[16  0  0]
 [ 0 17  0]
 [ 0  1 11]]
0.9777777777777777
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.94      1.00      0.97        17
           2       1.00      0.92      0.96        12

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.98        45
weighted avg       0.98      0.98      0.98        45



C:\Users\mallu\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [ ]:
Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in 
sklearn.datasets.

In [72]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
X,y=load_boston(return_X_y=True)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)
from sklearn.neighbors import KNeighborsRegressor
regressor=KNeighborsRegressor()
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

0.5748334691810936
4.148862275449102
32.17596886227545


C:\Users\mallu\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [ ]:
Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using 
cross-validation on load_iris dataset in sklearn.datasets.

In [82]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

x,y=load_iris(return_X_y=True)

X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3, random_state=0)
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier()

In [83]:
## Hypeparameter Tuning
params={'n_neighbors':[3,5,10,100],
              'algorithm':['ball_tree','kd_tree'],
               'p':[1,2]
              }

In [84]:
from sklearn.model_selection import RandomizedSearchCV

In [85]:
KNN_cls=RandomizedSearchCV(classifier,param_distributions=params,scoring='accuracy',cv=5,verbose=3)

In [86]:
KNN_cls.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END algorithm=kd_tree, n_neighbors=10, p=1;, score=0.952 total time=   0.0s
[CV 2/5] END algorithm=kd_tree, n_neighbors=10, p=1;, score=1.000 total time=   0.0s
[CV 3/5] END algorithm=kd_tree, n_neighbors=10, p=1;, score=1.000 total time=   0.0s
[CV 4/5] END algorithm=kd_tree, n_neighbors=10, p=1;, score=0.905 total time=   0.0s
[CV 5/5] END algorithm=kd_tree, n_neighbors=10, p=1;, score=0.952 total time=   0.0s
[CV 1/5] END algorithm=ball_tree, n_neighbors=3, p=2;, score=0.857 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, n_neighbors=3, p=2;, score=1.000 total time=   0.0s
[CV 3/5] END algorithm=ball_tree, n_neighbors=3, p=2;, score=1.000 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, n_neighbors=3, p=2;, score=0.905 total time=   0.0s
[CV 5/5] END algorithm=ball_tree, n_neighbors=3, p=2;, score=0.952 total time=   0.0s
[CV 1/5] END algorithm=kd_tree, n_neighbors=5, p=2;, score=0.952 total time=   0.0s


C:\Users\mallu\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\mallu\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(),
                   param_distributions={'algorithm': ['ball_tree', 'kd_tree'],
                                        'n_neighbors': [3, 5, 10, 100],
                                        'p': [1, 2]},
                   scoring='accuracy', verbose=3)

In [87]:
KNN_cls.best_params_

{'p': 2, 'n_neighbors': 5, 'algorithm': 'kd_tree'}

### Optimum value of k is 5

In [ ]:
Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in 
sklearn.datasets.

In [95]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

X,y=load_boston(return_X_y=True)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

from sklearn.preprocessing import StandardScaler

scalar=StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.fit_transform(X_test)

regressor=KNeighborsRegressor()
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

0.7467624886127056
2.7128143712574846
19.164637125748506


C:\Users\mallu\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [ ]:
Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on 
load_iris dataset in sklearn.datasets.

In [96]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

x,y=load_iris(return_X_y=True)

X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3, random_state=0)
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(weights='distance')
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[16  0  0]
 [ 0 17  0]
 [ 0  1 11]]
0.9777777777777777
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.94      1.00      0.97        17
           2       1.00      0.92      0.96        12

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.98        45
weighted avg       0.98      0.98      0.98        45



In [ ]:
Q6. Implement a function to standardise the features before applying KNN classifier.

In [97]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

x,y=load_iris(return_X_y=True)

X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3, random_state=0)

scalar=StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.fit_transform(X_test)


from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(weights='distance')
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[16  0  0]
 [ 0 13  0]
 [ 0  5 11]]
0.8888888888888888
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.72      1.00      0.84        13
           2       1.00      0.69      0.81        16

    accuracy                           0.89        45
   macro avg       0.91      0.90      0.88        45
weighted avg       0.92      0.89      0.89        45



In [ ]:
Q7. Write a Python function to calculate the euclidean distance between two points.

In [99]:
import math

p = [3, 3]
q = [6, 12]

print (math.dist(p, q))

9.486832980505138


In [ ]:
Q8. Write a Python function to calculate the manhattan distance between two points.

In [ ]:
import math

p = [3, 3]
q = [6, 12]

print (math.dist(p, q))

In [100]:
# Calculating Manhattan Distance from Scratch
def manhattan_distance(point1, point2):
    distance = 0
    for x1, x2 in zip(point1, point2):
        difference = x2 - x1
        absolute_difference = abs(difference)
        distance += absolute_difference

    return distance

In [101]:
manhattan_distance(p, q)

12